# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84570babd6fb9307332673fccde8b0c02099a3efb9193777afcd71896816e0e7d40bfe7bfef58176c3edb0fd32944889048c201f20fdf473789af68edb312842

test:
  secret_key_base: 0f3450978dd0b8f99a6dc5261430bea7cf1896a5b0302011e78858fdaab6e3817a031a1a4921505fba487d1adda4f0f4c60fe477b5a886fcafa4819f865ea956

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
